<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mminteractive"
 *
 * Auto generated by Extension Builder 2015-02-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'MM Interactive',
    'description' => 'A Typo3 Extension for creating and changing interactive areas on web pages',
    'category' => 'plugin',
    'author' => 'Michael Perlbach',
    'author_email' => 'info@mikelmade.de',
    'author_company' => 'MikelMade',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => 'uploads/tx_mminteractive',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-7.9.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
    'version' => '0.0.1',
);

?>